# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pfpj',
            field=models.CharField(choices=[('PF', 'Pessoa f\xedsica'), ('PJ', 'Pessoa jur\xeddica')], default='PF', max_length=1),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='pfpj',
            field=models.CharField(choices=[('PF', 'Pessoa f\xedsica'), ('PJ', 'Pessoa jur\xeddica')], default='PF', max_length=1),
        ),
    ]
