# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0002_auto_20180707_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superuber.Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superuber.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salary',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='terceirizado',
            field=models.CharField(choices=[('T', 'Terceirizado'), ('E', 'Efetivo')], default='E', max_length=1),
            preserve_default=False,
        ),
    ]
