# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0005_auto_20180707_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
